### ISSUE TITLE
project_init.sh does not run

### ISSUE THREAD

**Issue by DLorell** [sagemathinc/cocalc-docker#163]
Sorry if this is obvious, and I hope it is.

I cannot for the life of me get https://doc.cocalc.com/project-init.html this functionality to work. I've maximally permissive permissions, different permutations of group/user ownership... I tested the script manually (and it worked).

Is this feature removed from the containerized version of cocalc?

**Comment by williamstein** [comment]
> Is this feature removed from the containerized version of cocalc?

Evidently it wasn't ever implemented there:

```sh
~/cocalc/src$ git grep project_init
~/cocalc/src$ 
```

It would be very reasonable to change our implementation or do a new implementation where the project node.js server itself is responsible for running that script, instead of whatever currently does it in our Kubernetes cluster.  Thus I've created:

https://github.com/sagemathinc/cocalc/issues/6083
