### ISSUE TITLE
'metrics' page visible

### ISSUE THREAD

**Issue by vdtoorn** [sagemathinc/cocalc-docker#164]
The institution I work in alerted me to the fact that you can see the 'metrics' page as a security concern, because hackers may use it as a starting point for further research. They reference:

https://hackerone.com/reports/1026196

as relevant to this alert.

Is it possible to switch off the metrics page in Cocalc docker?

**Comment by williamstein** [comment]
Precisely what page are you referring to?

**Comment by williamstein** [comment]
OK, thanks for the clarification -- it's the page with data used by prometheus monitoring.    There's currently no way to disable that page, which comes from our prometheus monitoring support.  I've created an issue 

https://github.com/sagemathinc/cocalc/issues/6095

to make it something that is disabled by default, and can optionally be enabled by an admin.  It should really just be off by default.  I'll close this issue here when the above issue is fixed and a new version of cocalc-docker with it merged is available.

Thanks for reporting this.

**Comment by vdtoorn** [comment]
Great, thanks for the fast response!

**Comment by williamstein** [comment]
Now fixed! Go here to see the new default:  https://cocalc.sagemath.org/metrics

**Comment by vdtoorn** [comment]
Impressive speed! Op 1 sep. 2022 22:15 schreef William Stein ***@***.***>:
Now fixed! Go here to see the new default:  https://cocalc.sagemath.org/metrics
