### ISSUE TITLE
Connecting/disconnected cycle on sign-in page

### ISSUE THREAD

**Issue by barriecooper** [sagemathinc/cocalc-docker#19]
Hi,

I hope I'm posting in the right place. I love having CoCalc locally via docker.

I've just pulled the latest version of cocalc as per the instructions, but now it won't log me in to the new version of the server due to connection problems.  The connection never seems to get up and running and remains in a cycle of "connecting" and "disconnected".

I've just checked the cocalc-dev branch and that is working fine for me (same machine, running Ubuntu and using Chromium as browser) - that branch hasn't been pushed to dockerhub so recently.

Thanks for all your work on making this available,

Barrie.

**Comment by nvcleemp** [comment]
I actually have the same issue. The yellow rectangle in the upper right corner is stuck on connecting. If I look at the logs, this message is printed repeatedly.

> 2018-12-03T08:56:20.726Z - debug: PostgreSQL._do_connect: "Failed to connect to database -- command 'psql' (args=--user smc --host /projects/postgres/data/socket --port 5432 --list --tuples-only) exited with nonzero code 2 -- stderr='psql: could not connect to server: Connection refused\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket \"/projects/postgres/data/socket/.s.PGSQL.5432\"?\n'"
Failed to connect to database -- command 'psql' (args=--user smc --host /projects/postgres/data/socket --port 5432 --list --tuples-only) exited with nonzero code 2 -- stderr='psql: could not connect to server: Connection refused
	Is the server running locally and accepting
	connections on Unix domain socket "/projects/postgres/data/socket/.s.PGSQL.5432"?

I have checked out the latest version and recreated the container. This has worked for me in the past, but since a couple of months (maybe half a year) I'm no longer able to sign in to my local CoCalc installation due to this issue.
