### ISSUE TITLE
Unable to view PDF files in projects and LaTeX editor

### ISSUE THREAD

**Issue by ktaletsk** [sagemathinc/cocalc-docker#24]
- Click on any PDF file in project -> It is stuck in Loading loop forever

- In LaTeX editor, PDF (Preview) sometimes does not show anything. Seem to be fixed by removing all auxilary files and recompiling document. When it works and document is updated, Preview does not reflect the changes.

**Comment by williamstein** [comment]
This seems fixed.

**Comment by ktaletsk** [comment]
Thank you for your response. Opening of .pdf files works fine now. 
PDF Preview function inside of LaTeX editor is only partly fixed. It works as expected for short documents, but breaks for longer ones. I was able to reproduce the bug by creating .tex and pasting sample text (lorem ipsum) multiple times until the preview functionality breaks. After my document reached 23 pages I was no longer able to get live preview of my document. As soon as I remove one paragraph so that document is shorter than 23 pages, it works fine again!

Please see this document by the link: https://gist.github.com/ktaletsk/94d25cff2073234a417fe72eb04be2dd

I certainly have problems with even shorter documents, so I am not sure what is broken there

**Comment by williamstein** [comment]
I cannot reproduce your problem.  Also, having just rewritten the latex editor and pdf previewer completely from scratch recently, I can think of no reason for a bug like you describe, except for something maybe specific to how you are running Docker.   I have hence labeled this a Heisenbug, meaning it is difficult to reproduce.  However, don't expect a fix from me without more information, since I can't reproduce it.

What I did:

1. Created a new .tex file on https://cocalc.com
2. Pasted your gist in and clicked "Build".
3. Saw 22 pages.
4. Uncommented last paragraph and clicked "Build".
5. Saw 23 pages.

I then did exactly the same again on my local Docker image.  In both cases it worked well for me.

![screenshot 2018-09-07 at 8 08 04 am](https://user-images.githubusercontent.com/1276278/45227381-3088f580-b275-11e8-8d7b-40e7fc6723c8.png)

You might try these steps and post the output of the Network console monitoring from Chrome -- that will show every single network request and what happened with it.  I think the only way a page wouldn't show up at this point would be if a network request failed for some reason, since all rendering of the PDF preview is now handled by pdf.js, which is a very robust and mature PDF rendering library (cocalc used to use a custom-from-scratch renderer that I wrote).

**Comment by ktaletsk** [comment]
Okay, you are absolutely right about the network problem. I am running my container behind Cloudflare proxy and when I go directly to my ip address, everything works fine. Problem solved

**Comment by williamstein** [comment]
Do you have the same problem with https://cocalc.com?  We run it behind a CloudFlare proxy as well.

**Comment by williamstein** [comment]
> I am running my container behind Cloudflare 

Which cloud host are you using, if any?  I wonder if we should have a md file about how to run cocalc-docker on various cloud hosts easily...

**Comment by ktaletsk** [comment]
@williamstein Just a Ubuntu desktop with a public IP. I had to use Cloudflare to circumvent certificate issue https://github.com/sagemathinc/cocalc/issues/2064
