### ISSUE TITLE
Cocalc jupyter process does not honor all user groups

### ISSUE THREAD

**Issue by apriori** [sagemathinc/cocalc-docker#76]
I currently attempt to mount an SMB share into the container that a project user can write into. While doing that I ran into the issue, that users are not persistent and only join a group with the user name. However, for decent smb share setup, all users would require to be in the same group. Cocalc docker does not allow for such a configuration. 

As a hacky workaround I wrapped "useradd" to always force a user to join the group "users". This has been verified to work when logged into the container externally, switched to the project user and entered group in the shell. However, any process in the web frontend remained having only the user specific group - no matter what I did.

So I assume there are bugs in the process groups assignment.

Are there any solutions to this?

**Comment by williamstein** [comment]
Hi @apriori  -- nobody has requested this before, and hence there's no completely trivial built in solution.  That said, the code that runs useradd is just this Python script:

https://github.com/sagemathinc/cocalc/blob/master/src/smc_pyutil/smc_pyutil/smc_compute.py#L232

and we could change it (though hopefully in a way that doesn't break all existing cocalc-docker containers).

You can experiment with changing it in your Docker container right now.  Become root in the docker container `sudo docker exec -it <name of your container> bash` and edit this file:

/usr/local/lib/python2.7/dist-packages/smc_pyutil/smc_pyutil.py

Then try making a new project and see what happens.   

I'm not opposed to changing things so all projects are part of the same group, rather than each having their own group, so long as that doesn't break things.  Alternatively, we could configure what happens via an environment variable, though that could get complicated.

**Comment by williamstein** [comment]
Updating my comment.  Now smc_compute.py (mentioned above) no longer exists.  Projects are started using the code here:

https://github.com/sagemathinc/cocalc/blob/master/src/smc-hub/project-control/multi-user.ts
